artifact_uri: localhost:5000/1/a595c1d6d4564cb5ac6d1a3f415a57f4/artifacts
end_time: 1635483017696
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: a595c1d6d4564cb5ac6d1a3f415a57f4
run_uuid: a595c1d6d4564cb5ac6d1a3f415a57f4
source_name: ''
source_type: 4
source_version: ''
start_time: 1635483015127
status: 4
tags: []
user_id: chrysostome
