artifact_uri: localhost:5000/1/9d771cdcad604879822bfe1fb09edb92/artifacts
end_time: 1635481357580
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 9d771cdcad604879822bfe1fb09edb92
run_uuid: 9d771cdcad604879822bfe1fb09edb92
source_name: ''
source_type: 4
source_version: ''
start_time: 1635481355384
status: 4
tags: []
user_id: chrysostome
