artifact_uri: localhost:5000/0/c944afbac8d24fc6ba81882a6e447cda/artifacts
end_time: 1635483041120
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: c944afbac8d24fc6ba81882a6e447cda
run_uuid: c944afbac8d24fc6ba81882a6e447cda
source_name: ''
source_type: 4
source_version: ''
start_time: 1635483038671
status: 4
tags: []
user_id: chrysostome
