artifact_uri: localhost:5000/1/08bf1ae92ed6475390865f180c6a5ffd/artifacts
end_time: null
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 08bf1ae92ed6475390865f180c6a5ffd
run_uuid: 08bf1ae92ed6475390865f180c6a5ffd
source_name: ''
source_type: 4
source_version: ''
start_time: 1635480983557
status: 1
tags: []
user_id: chrysostome
