defaults:
- var: env
- data: v1
- run: default
experiment: gojob
flow_id: None
last_model: None
project_path: /home/chrysostome/Desktop/test_gojob/gojob/project
repo: /home/chrysostome/Desktop/test_gojob/gojob
